// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemasTutorInteligente.Models;

namespace SistemasTutorInteligente.Migrations
{
    [DbContext(typeof(SistemasTutorInteligenteContext))]
    [Migration("20181112211752_[sistema]")]
    partial class sistema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemasTutorInteligente.Models.curso", b =>
                {
                    b.Property<int>("IDcurso")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nivel")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<string>("nombre_curso")
                        .IsRequired()
                        .HasMaxLength(95);

                    b.HasKey("IDcurso");

                    b.ToTable("curso");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.DatosCuenta", b =>
                {
                    b.Property<int>("IDusuario")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password");

                    b.Property<string>("Usuario");

                    b.HasKey("IDusuario");

                    b.ToTable("DatosCuenta");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.DatosPersonales", b =>
                {
                    b.Property<int>("IDdatos")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Amaterno");

                    b.Property<string>("Apaterno");

                    b.Property<int>("Edad");

                    b.Property<int>("IDusuario");

                    b.Property<string>("Nombre");

                    b.HasKey("IDdatos");

                    b.HasIndex("IDusuario");

                    b.ToTable("DatosPersonales");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.Ejercicio", b =>
                {
                    b.Property<int>("IDejercicio")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NombreEjercicio")
                        .IsRequired()
                        .HasMaxLength(45);

                    b.Property<int>("Puntaje");

                    b.HasKey("IDejercicio");

                    b.ToTable("Ejercicio");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.preguntas_test_inteligencia", b =>
                {
                    b.Property<int>("IDpreguntas_test")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("num_pregunta");

                    b.Property<string>("pregunta");

                    b.HasKey("IDpreguntas_test");

                    b.ToTable("preguntas_test_inteligencia");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.tema_curso", b =>
                {
                    b.Property<int>("IDtemas")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("IDcurso");

                    b.Property<string>("nombre_tema")
                        .IsRequired()
                        .HasMaxLength(95);

                    b.HasKey("IDtemas");

                    b.HasIndex("IDcurso");

                    b.ToTable("tema_curso");
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.DatosPersonales", b =>
                {
                    b.HasOne("SistemasTutorInteligente.Models.DatosCuenta", "datosCuenta")
                        .WithMany("datosPersonales")
                        .HasForeignKey("IDusuario")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SistemasTutorInteligente.Models.tema_curso", b =>
                {
                    b.HasOne("SistemasTutorInteligente.Models.curso", "curso")
                        .WithMany("tema_curso")
                        .HasForeignKey("IDcurso")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
